on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.honki.ng
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install docker pyyaml
      - name: Build and push Docker images
        run: |
          python build.py
        env:
          IMAGE_NAME: registry.honki.ng/minecraft-server
